Add backport config and update readme
goharbor/website pull request #129
Opened 2020-10-26 11:08 UTC by a-mccarthy

Signed-off-by: Abigail McCarthy <mabigail@vmware.com>

2020-10-26 12:18 UTC, a-mccarthy commented
@jonasrosland can you review this please? I was also think that it might be helpful to add a PR template so we can (hopefully) capture which branches changes should be backported into. Or maybe add labels to PRs? thoughts?

2020-10-26 18:32 UTC, jonasrosland requested changes
I think this looks great, just 2 small edits needed IMO

2020-10-26 18:32 UTC, jonasrosland commented on README.md
> +If you are making a change that is specific to a single released version of documentation, make a PR against that branch (`release-X`).
Can we clarify that this should only be done if the content isn't going to be used for any future versions? Like, this is a bugfix in the docs for 1.10, that's ok, but a small fix for 2.1 should most likly go into master/main and then backported, right?

2020-10-26 18:32 UTC, jonasrosland commented on README.md
> +After a releases, update the `.backportrc.json` file with the new release branch.
Missing some words :)

2020-10-26 18:33 UTC, jonasrosland commented
> @jonasrosland can you review this please? I was also think that it might be helpful to add a PR template so we can (hopefully) capture which branches changes should be backported into. Or maybe add labels to PRs? thoughts?

I think adding labels would make it clear when we do a glance over the new PRs, and adding a new PR template is a good idea too.

2020-10-28 14:06 UTC, jonasrosland approved these changes

2020-10-28 14:07 UTC, merged