Fix links to upgrade guides for previous versions
goharbor/website pull request #332
Opened 2022-04-21 15:37 UTC by Yorwba

I assume the version number mismatch was due to a simple copy-paste error.

2022-04-27 08:24 UTC, OrlinVasilev commented
@Yorwba please fix your signature and will approve!

2022-04-27 08:24 UTC, OrlinVasilev requested changes
DCO fix needed

2022-05-12 10:47 UTC, OrlinVasilev approved these changes
lgtm

2022-05-12 17:39 UTC, a-mccarthy approved these changes
lgtm! thanks!

2022-05-12 17:39 UTC, merged