Bind host to 0.0.0.0
goharbor/website pull request #376
Opened 2022-10-28 08:14 UTC by AllForNothing

1. Bind host to 0.0.0.0 for `hugo server` command.  Then users can visit the server by `http://localhost:1313` or   `http://<ip>:1313`. The latter is often used for remote access
Signed-off-by: AllForNothing <sshijun@vmware.com>

2022-10-28 11:01 UTC, OrlinVasilev requested changes

2022-10-28 11:01 UTC, OrlinVasilev commented on Makefile
> +        --bind 0.0.0.0 \
please fix the indentation 
```suggestion
		--bind 0.0.0.0 \
```

2022-10-31 00:40 UTC, AllForNothing commented on Makefile
> +        --bind 0.0.0.0 \
Fixed

2022-10-31 01:15 UTC, yanji09 approved these changes

2022-11-01 12:52 UTC, OrlinVasilev approved these changes
lgtm

2022-11-01 12:52 UTC, merged