Update registry landscape table
goharbor/website pull request #421
Opened 2023-02-15 12:13 UTC by matofeder

This PR updates some project Quay-related features in the registry landscape table.
Some differences have been found in the recent [overview](https://github.com/SovereignCloudStack/standards/blob/079b16291f89aa087840ec8f1b40bee3040c9a06/Decisions/scs-XXXX-v1-requirements-for-container-registry.md) of the open-source container registries within SCS project.

Find the list of modified Quay features and comments below:

1. _Content Trust and Validation_  

- It seems that support for cosign is there since [Quay v3.6](https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/use_red_hat_quay/oci-intro#cosign-oci-with-quay) (as v3.5 did not mention it) 

- See the print screen from my quick test below: 
![image](https://user-images.githubusercontent.com/17620218/219016758-610df5eb-9591-461d-88e6-dddccd021608.png)
 
- I'm not sure whether this integration of Cosign in Quay is comparable with the Notary+Cosign support in Harbor and if the statement "Content Trust and Validation are supported in Quay" is really true. From my perspective, this looks comparable, but I'm not an experienced Harbor user. 

2. _Project Quotas (by image count & storage consumption)_

- Support for quota management based on storage consumption is there since [Quay v3.7](https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay/index#red-hat-quay-quota-management-and-enforcement)

- This row in the table was filled with the string "partial" as the quota management based on image count is not supported in Quay

3. _Upstream Registry Proxy Cache_ -  

- Quay supports [proxy cache]https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay/index#quay-as-cache-proxy)

- This feature is still marked as `Technology Preview`, see the [note](https://access.redhat.com/documentation/en-us/red_hat_quay/3.7/html-single/use_red_hat_quay/index#quay-as-cache-proxy) in the related docs

-This row in the table was filled with the "✓" as I assumed that this table does not evaluate the maturity of mentioned features

2023-02-17 15:47 UTC, Vad1mo approved these changes
thx

2023-02-20 14:33 UTC, OrlinVasilev requested changes

2023-02-20 14:33 UTC, OrlinVasilev commented on docs/build-customize-contribute/registry-landscape.md
> +| Upstream Registry Proxy Cache                          | ✓      | ✓                       | ✓       | ✗                                 | ✓                           | ✓           | ✗        |
please update it when it's GAed, thank you!

2023-03-24 10:20 UTC, OrlinVasilev approved these changes

2023-03-24 10:20 UTC, merged

2023-03-24 10:21 UTC, OrlinVasilev commented
@matofeder  thank you for your contributions :)