Enhance the explanation for the group filter
goharbor/website pull request #503
Opened 2023-10-26 02:39 UTC by AllForNothing

1. Fixes https://github.com/goharbor/harbor/issues/19419

2023-10-26 05:37 UTC, OrlinVasilev commented on docs/administration/configure-authentication/oidc-auth.md
> +   - **OIDC Group Filter**: The [regular expression](https://pkg.go.dev/regexp/syntax) to filter OIDC groups.Only the groups that match the provided regular express will be added to Harbor. It only f
```suggestion
   - **OIDC Group Filter**: The [regular expression](https://pkg.go.dev/regexp/syntax) to filter OIDC groups.Only the groups that match the provided regular express will be added to Harbor. It only filters the groups and doesn’t limit the user's login to Harbor.
```

2023-10-26 05:37 UTC, OrlinVasilev commented
@AllForNothing added comment

2023-10-26 06:15 UTC, Vad1mo requested changes
The whole text is a bit off:
It misses: 

- On what data/source it is filtering on? -> «Group Claim Name»
- What will happen with the filtered result -> Groups are added to Harbor 


What about this:

```
**OIDC Group Filter**: A [regular expression](https://pkg.go.dev/regexp/syntax) to select matching groups from the «Group Claim Name» list 
. Matching groups are added to Harbor. This filter does not limit the users' capability to log in into Harbor.
```

2023-10-27 05:32 UTC, OrlinVasilev approved these changes

2023-11-13 07:26 UTC, Vad1mo approved these changes

2023-11-13 09:15 UTC, merged