Adding section how to work with OCI helm charts
goharbor/website pull request #513
Opened 2023-11-17 10:45 UTC by OrlinVasilev

2023-11-18 20:28 UTC, OrlinVasilev commented
@Vad1mo @wy65701436 can you please check if it makes sense to have to that here will add some screen shots from the UI as well

2023-11-19 10:32 UTC, Vad1mo requested changes
This is valuable. 
I have only one question, why is the same content twice but in different locations?

2023-11-20 13:12 UTC, OrlinVasilev commented
@Vad1mo  it's a mistake of course :) started at one place and moved it to another without actually fixing it :) thanks!

2023-11-20 14:41 UTC, Vad1mo approved these changes
very nice

2023-11-21 07:00 UTC, zyyw commented on docs/working-with-projects/working-with-oci/working-with-helm-oci-charts.md
> +helm pull oci://demo.goharbor.io/oci/demo --version 0.1.0
maybe change `oci://demo.goharbor.io/oci/demo` to `oci://demo.goharbor.io/oci/oci-charts` to make it consistent between the `docs/img/oci/oci-chart-main-view.png` image and the text.

2023-11-21 07:02 UTC, zyyw commented on docs/working-with-projects/working-with-oci/working-with-helm-oci-charts.md
> +helm push example-0.1.0.tgz oci://demo.goharbor.io/oci
maybe change `helm push example-0.1.0.tgz oci://demo.goharbor.io/oci` to `helm push oci-chart-example-0.1.0.tgz oci://demo.goharbor.io/oci-charts` to make it consistent between the `docs/img/oci/oci-chart-main-view.png` image and the text.

2023-11-21 07:03 UTC, zyyw approved these changes
LGTM, while left some comments

2023-11-21 07:03 UTC, merged