Update for the system robot account and the project robot account sections
goharbor/website pull request #517
Opened 2023-12-08 05:43 UTC by AllForNothing

1. Fixes https://github.com/goharbor/harbor/issues/19354

This is how the `Permission References` tables look like:
![Screenshot 2023-12-08 at 13 47 42](https://github.com/goharbor/website/assets/30999793/7a76fa38-8037-46b3-bd86-2539a8e3e0fc)

2023-12-14 08:30 UTC, OrlinVasilev commented on docs/administration/robot-accounts/_index.md
> +![System robot account page](../../img/robotaccount/system-robot-account-page.png)
can you change that to robot-account so we can keep the directory naming consistent, thank you!

2023-12-14 08:30 UTC, OrlinVasilev commented on docs/administration/robot-accounts/_index.md
> +![System robot account page](../../img/robotaccount/system-robot-account-page.png)
and for all pictures

2023-12-14 23:20 UTC, Vad1mo requested changes

2023-12-14 23:20 UTC, Vad1mo commented on docs/administration/robot-accounts/_index.md
> +You can refer to the [**Permission References**](#permission-references) to assign a combination of these permissions to a system robot account to perform your desired tasks through the OCI client or
The [**Permission References**](#permission-references) contains a list of permission and their operations. A combination of these permissions can be assigned to a system robot account to perform your desired tasks through an OCI client, or the Harbor API. Robot Accounts cannot be used to log in into the user interface.

2023-12-14 23:20 UTC, Vad1mo commented on docs/administration/robot-accounts/_index.md
>  1. Log into your harbor instance as an administrator.
Harbor is a name, so first latter in capital: > Log into your Harbor instance as an administrator.

2023-12-14 23:20 UTC, Vad1mo commented on docs/administration/robot-accounts/_index.md
>  1. Go to **Robot Accounts** item under **Administration**.
1. In the sidebar select **Robot Accounts** in the **Administration** section.

2023-12-14 23:20 UTC, Vad1mo commented on docs/administration/robot-accounts/_index.md
This page contains the lists of all existing system robot accounts in your Harbor instance. The table contains the following information for each system robot account:

2023-12-14 23:20 UTC, Vad1mo commented on docs/administration/robot-accounts/_index.md
> +* The number of system permissions an account is assigned to. To see a full set of the assigned system permissions, click on the **PERMISSIONS** link.
* Enabled status shows if an account is active or deactivated.

2023-12-14 23:20 UTC, Vad1mo commented on docs/administration/robot-accounts/_index.md
* The created time shows when the robot account was created.
* The account expiration time. Calculated based on the created time and the expiration time set when creating the robot account.
* The manually added description for the system robot account.

2023-12-14 23:20 UTC, Vad1mo commented on docs/administration/robot-accounts/_index.md
>  1. Click **New Robot Account**.
1. Log in to the Harbor user interface, with system administrator privileges.
1. Go to **Administration**, select a project, and select **Robot Accounts**.
1. Click **New Robot Account**.

2023-12-14 23:20 UTC, Vad1mo commented on docs/administration/robot-accounts/_index.md
> +Public APIs are not included in the tables above because they can be accessed by any robot account
Public APIs are not included in the tables above because they can be accessed by any robot account.

Any robot account or anyone?

2023-12-19 03:06 UTC, stonezdj approved these changes

2023-12-19 03:08 UTC, stonezdj commented
Hi, @Vad1mo @OrlinVasilev  I 'll merge the current PR and raise another PR to fix issues mentioned in your comments.

2023-12-19 03:17 UTC, wy65701436 approved these changes
lgtm

2023-12-19 03:18 UTC, merged