Fix youtube frame not responsive
goharbor/website pull request #586
Opened 2024-10-29 16:44 UTC by Insomniac2904

Resolves issue #582 
Fixes Youtube iframe bleeding out in [homepage](https://goharbor.io/) and [cosine page](https://goharbor.io/blog/cosign-2.5.0/) when the page size is very small.

2024-11-04 15:35 UTC, Insomniac2904 commented
@AllForNothing can you check this PR. It has been pending for about a week. Do tell me if there is any issue. I am new to contributing. Thanks.

2024-11-15 11:07 UTC, bupd approved these changes
LGTM!

2024-11-18 12:46 UTC, Insomniac2904 commented
> LGTM!

hey @bupd can you tell me how to remove the license compliance error.

2025-01-16 01:17 UTC, AllForNothing commented
@ Insomniac2904 Could you provide some screenshots after you've fixed it?

2025-01-17 08:22 UTC, Insomniac2904 commented
> @ Insomniac2904 Could you provide some screenshots after you've fixed it?

Pages changed:
/blog/cosign-2.5.0/
home page

Normal View

![Screenshot from 2025-01-17 13-47-16](https://github.com/user-attachments/assets/793a2881-445c-4fc1-ac69-990411b4ba71)

Decreased the width

![Screenshot from 2025-01-17 13-47-31](https://github.com/user-attachments/assets/0eb5f9c1-1d80-4927-a877-3d9375dc166a)

2025-01-17 11:26 UTC, OrlinVasilev commented
Good Stuff @bupd can you fix on the blog the missing picture part 
Line 8:  ![Cosign](https://raw.githubusercontent.com/sigstore/cosign/main/images/logo.svg)

so we can have it on go thanks

2025-01-17 12:35 UTC, OrlinVasilev requested changes
please update logo.svg with valid one :) thanks

2025-01-20 08:28 UTC, bupd commented
> can you fix on the blog the missing picture part Line 8: ![Cosign](https://raw.githubusercontent.com/sigstore/cosign/main/images/logo.svg)
> 
> so we can have it on go thanks


@OrlinVasilev Fixed it. Thanks

2025-01-20 12:28 UTC, OrlinVasilev commented
thank you @Insomniac2904 :) and @bupd

2025-01-20 12:30 UTC, OrlinVasilev approved these changes

2025-01-20 15:34 UTC, Vad1mo approved these changes

2025-01-20 15:34 UTC, merged